### Site info:
title: Infrastructure as Code
tagline: Information about the book by Kief Morris
author: Kief Morris
email: site@infrastructure-as-code.com
description: "Information about Infrastructure as Code, supporting the book by Kief Morris"
keywords: "infrastructure as code, infrastructure, cloud, automation, book, devops, automation, virtualization"
baseurl: ""
url: "https://infrastructure-as-code.com"

# Pattern catalog
collections:
  patterns:
    output: true
    permalink: /patterns/:path.html

# Don't copy stuff
exclude: [ "*.sh", "*.json", "LICENSE", "README", "bin" ]

### Personal info and site tools info:
twitter_username: kief
github_username:  kief
favicon:     "/images/favicon.ico"
aboutme_photo: "/images/kief_profile_small.jpg"


### Site setting:
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.

Links:
  - name: DevOpsDays
    href: http://DevOpsDays.org
    title: DevOpsDays website
  - name: Kief's website
    href: http://kief.com/
    title: Kief's website
  - name: ThoughtWorks infrastructure as code page
    href: https://info.thoughtworks.com/Infrastructure-as-Code-Kief-Morris.html
    title: ThoughtWorks infrastructure as code page


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5

plugins:
  - jekyll-sitemap
  - jekyll-paginate
