:source-highlighter: pygments

= Pattern: Reusable Stack

It can be useful to design and implement a [stack](README.adoc) definition so that it can be easily used to create multiple stack instances. Two main reasons for doing this are for testing, and for code re-use.

When making changes to an infrastructure stack definition, being able to provision a test instance enables you to test your changes before applying them to your production stack instance. As an individual engineer making changes to infrastructure code, you can provision and test your changes on your own sandbox instance before committing changes. As a team, you can use [Continuous Integration](https://martinfowler.com/articles/continuousIntegration.html) and [Continuous Delivery](https://martinfowler.com/bliki/ContinuousDelivery.html) to facilitate a consistent and reliable process for testing and delivering changes to your infrastructure. There are a number of considerations for [testing infrastructure changes](../stack-testing/README.adoc) effectively.

For infrastructure that is used to run software developed by other teams, using the same stack definition to create instances for various test and review environments (e.g. "dev", "qa", "staging", "preprod", "uat", etc.) ensures that any given build of the software is running on a production-like environment. Delivering software and infrastructure changes through [pipelines](../stack-pipelines) can make change management and release processes easier, faster, more reliable, and more compliant.




It is often useful to define basic, re-usable stack code that can be customized to define different stacks with more specific attributes. For example, you may define a stack that defines a load balancer, but allow it to be customized to manage different types of network traffic. A basic load balancer stack might be used to create an HTTP load balancer. This stack could then be extended to create an HTTPS load balancer, adding configuration and code to provision SSL certificates.


Defining an [infrastructure stack](definition-of-a-stack.adoc) as code enables the creation of multiple instances of that stack. There are a number of reasons where this is useful. One is to create


This might be used as an [environment template](environment-template.adoc), to replicate a stack instance in multiple environments, or else as a [library stack](library-stack.adoc) that can be re-used for different things.


A  definition can be used to create multiple instances of 


== Alternative to:

- Stack Module (re-uses infrastructure code at a different level)
- Singleton Stack (maintain a single stack definition for each stack instance)


== Things to consider

Avoid conflicts when multiple instances of the stack definition are created, e.g. names and IDs.


== Parameterized Stacks

Define parameters as part of the stack definition, pass in values for these parameters when creating a stack instance.

Specific types of re-usable stacks:


== Intent

(1-2 sentences)

Diagram

== Intro

== How

(to implement / use the pattern)

== When

(to use the pattern)
